CREATE SCHEMA production;
CREATE SCHEMA sales;

CREATE TABLE sales.stores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    phone character varying(25),
    email character varying(255),
    street character varying(255),
    city character varying(255),
    state character varying(10),
    zip_code character varying(5)
);

CREATE TABLE production.brands (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL
);

CREATE TABLE production.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL
);

CREATE TABLE production.products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    brand_id integer NOT NULL REFERENCES production.brands(id) ON DELETE CASCADE ON UPDATE CASCADE,
    category_id integer NOT NULL REFERENCES production.categories(id) ON DELETE CASCADE ON UPDATE CASCADE,
    model_year smallint NOT NULL,
    price numeric(10,2) NOT NULL
);

CREATE TABLE production.stocks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id integer REFERENCES sales.stores(id) ON DELETE CASCADE ON UPDATE CASCADE,
    product_id integer REFERENCES production.products(id) ON DELETE CASCADE ON UPDATE CASCADE,
    quantity integer
);

CREATE TABLE sales.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone character varying(25),
    email character varying(255) NOT NULL,
    street character varying(255),
    city character varying(50),
    state character varying(25),
    zip_code character varying(5)
);


CREATE TABLE sales.staffs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    phone character varying(25),
    active smallint NOT NULL,
    store_id integer NOT NULL REFERENCES sales.stores(id) ON DELETE CASCADE ON UPDATE CASCADE,
    manager_id integer REFERENCES sales.staffs(id)
);

CREATE TABLE sales.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer REFERENCES sales.customers(id) ON DELETE CASCADE ON UPDATE CASCADE,
    order_status smallint NOT NULL,
    order_date date NOT NULL,
    required_date date NOT NULL,
    shipped_date date,
    store_id integer NOT NULL REFERENCES sales.stores(id) ON DELETE CASCADE ON UPDATE CASCADE,
    staff_id integer NOT NULL REFERENCES sales.staffs(id)
);

CREATE TABLE sales.order_items (
    order_id integer NOT NULL REFERENCES sales.orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
    product_id integer NOT NULL REFERENCES production.products(id) ON DELETE CASCADE ON UPDATE CASCADE,
    quantity integer NOT NULL,
    list_price numeric(10,2) NOT NULL,
    discount numeric(4,2) NOT NULL DEFAULT 0,
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
